name: "Build vcpkg dependencies"
description: "Build vcpkg dependencies"
inputs:
  vcpkg-binary:
    description: "Vcpkg binary"
    required: true
    default: "vcpkg"
  rust-target:
    description: "Cargo target triplet"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install cargo-vcpkg
      uses: taiki-e/cache-cargo-install-action@v3
      with:
        tool: cargo-vcpkg
    - name: Get vcpkg info
      shell: bash
      id: vcpkg-info
      run: |
        echo "tag=$(yq '.package.metadata.vcpkg.rev' nghe-backend/Cargo.toml)" >> "$GITHUB_OUTPUT"
        echo "root=${{ github.workspace }}/$(yq '.env.VCPKG_ROOT.value' .cargo/config.toml)" >> "$GITHUB_OUTPUT"
    - name: Download vcpkg
      uses: actions/checkout@v6
      with:
        repository: "microsoft/vcpkg"
        ref: ${{ steps.vcpkg-info.outputs.tag }}
        path: ${{ inputs.vcpkg-root }}
    - name: Bootstrap vcpkg Unix
      if: runner.os != 'Windows'
      shell: bash
      run: ${{ steps.vcpkg-info.outputs.root }}/bootstrap-vcpkg.sh
    - name: Add vcpkg cache Unix
      if: runner.os != 'Windows'
      shell: bash
      env:
        VCPKG_EXE: ${{ steps.vcpkg-info.outputs.root }}/${{ inputs.vcpkg-binary }}
        USERNAME: ${{ github.actor }}
        FEED_URL: https://nuget.pkg.github.com/${{ github.actor }}/index.json
      run: |
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          sources add \
          -Source "${{ env.FEED_URL }}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ env.USERNAME }}" \
          -Password "${{ secrets.GITHUB_TOKEN }}"
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -Source "${{ env.FEED_URL }}"
    - name: Bootstrap vcpkg Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: ${{ steps.vcpkg-info.outputs.root }}/bootstrap-vcpkg.bat
    - name: Add vcpkg cache Windows
      if: runner.os == 'Windows'
      shell: bash
      env:
        VCPKG_EXE: ${{ steps.vcpkg-info.outputs.root }}/${{ inputs.vcpkg-binary }}
        USERNAME: ${{ github.actor }}
        FEED_URL: https://nuget.pkg.github.com/${{ github.actor }}/index.json
      run: |
        .$(${{ env.VCPKG_EXE }} fetch nuget) `
          sources add `
          -Source "${{ env.FEED_URL }}" `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName "${{ env.USERNAME }}" `
          -Password "${{ secrets.GITHUB_TOKEN }}"
        .$(${{ env.VCPKG_EXE }} fetch nuget) `
          setapikey "${{ secrets.GITHUB_TOKEN }}" `
          -Source "${{ env.FEED_URL }}"
    - name: Build vcpkg dependencies
      shell: bash
      run: |
        cargo vcpkg --verbose build --manifest-path nghe-backend/Cargo.toml --target ${{ inputs.rust-target }}
