[package]
name = "nghe_api"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
const_format = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }

nghe_proc_macro = { path = "../nghe-proc-macro" }

paste = "1.0.15"

[build-dependencies]
built = { version = "0.7.3", features = ["git2"] }
