name: "Install yq"
description: "Install yq"
runs:
  using: "composite"
  steps:
    - name: Install yq on ${{ runner.os }}
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get --assume-yes install yq
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install yq
        else
          brew install yq
        fi
