[package]
name = "nghe-frontend"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
concat-string.workspace = true
dioxus = { version = "0.5", features = ["web", "router"] }
dioxus-sdk = { version = "0.5.0", features = ["storage"] }
getrandom = { version = "0.2.14", features = ["js"] }
manganis = "0.2.2"
nghe-types = { path = "../types", default-features = false, features = [
  "frontend",
] }
rand.workspace = true
reqwest = "0.12.3"
serde.workspace = true
url = { version = "2.5.0", features = ["serde"] }

# Debug
log = "0.4.19"
dioxus-logger = "0.4.1"
console_error_panic_hook = "0.1.7"
