[package]
name = "nghe-frontend"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
concat-string.workspace = true
dioxus = { version = "0.5", features = ["web", "router"] }
manganis = "0.2.2"
nghe-types = { path = "../types", default-features = false, features = [
  "frontend",
] }
reqwest = "0.12.3"
url = "2.5.0"

# Debug
log = "0.4.19"
dioxus-logger = "0.4.1"
console_error_panic_hook = "0.1.7"
