[package]
name = "nghe-frontend"
version = { workspace = true }
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
concat-string = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }

nghe-types = { path = "../types" }

console_error_panic_hook = { verison = "0.1.7" }
dioxus = { version = "0.5.1", features = ["web", "router"] }
dioxus-logger = { version = "0.4.1" }
dioxus-sdk = { version = "0.5.0", features = ["storage"] }
getrandom = { version = "0.2.14", features = ["js"] }
log = { version = "0.4.19" }
manganis = { version = "0.2.2" }
reqwest = { version = "0.12.3" }
url = { version = "2.5.0", features = ["serde"] }
