workspace = { members = ["src/proc_macros"] }

[package]
name = "nghe"
version = "0.1.0"
edition = "2021"
default-run = "nghe"

[dependencies]
anyhow = "1.0.79"
axum = "0.7.3"
config = "0.13.4"
derivative = "2.2.0"
libaes = "0.7.0"
md5 = "0.7.0"
nghe-proc_macros = { path = "src/proc_macros", version = "0.1.0" }
paste = "1.0.14"
rand = "0.8.5"
sea-orm = { version = "0.12.10", features = [
  "sqlx-postgres",
  "runtime-tokio-native-tls",
  "macros",
  "with-uuid",
  "with-time",
] }
sea-orm-migration = "0.12.10"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5.0", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
built = "0.7"

[[bin]]
name = "nghe"
path = "src/main.rs"

[[bin]]
name = "sea-cli"
path = "src/migrator/main.rs"

[dev-dependencies]
serde_json = "1.0.111"
