[workspace]
members = ["frontend", "proc_macros", "types"]

[workspace.package]
version = "0.1.2"
edition = "2021"

[package]
name = "nghe"
version = { workspace = true }
edition = { workspace = true }

[workspace.dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
concat-string = { version = "1.0.1" }
constcat = { version = "0.5.0" }
derivative = { version = "2.2.0" }
hex = { version = "0.4.3" }
isolang = { version = "2.4.0", default-features = false, features = ["serde"] }
itertools = { version = "0.12.1" }
rand = { version = "0.8.5" }
serde = { version = "1.0.197", features = ["derive"] }
serde_with = { version = "3.7.0", features = ["hex"] }
strum = { version = "0.26.2", features = ["derive"] }
time = { version = "0.3.35", features = ["serde-human-readable", "macros"] }
uuid = { version = "1.8.0", features = ["serde"] }

# Dev
serde_json = { version = "1.0.115" }
fake = { version = "2.9.2", features = [
  "derive",
  "uuid",
  "serde_json",
  "time",
] }

[dependencies]
anyhow = { workspace = true }
concat-string = { workspace = true }
constcat = { workspace = true }
derivative = { workspace = true }
hex = { workspace = true }
isolang = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }

nghe-proc_macros = { path = "proc_macros" }
nghe-types = { path = "types" }

async-trait = { version = "0.1.79" }
axum = { version = "0.7.5", features = ["http2", "macros"] }
axum-extra = { version = "0.9.3", features = ["form"] }
diesel = { version = "2.1.5", features = ["time", "uuid"] }
diesel-async = { version = "0.4.1", features = [
  "postgres",
  "deadpool",
  "async-connection-wrapper",
] }
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
figment = { version = "0.10.16", features = ["env"] }
flume = { version = "0.11.0", features = ["async"] }
futures = { version = "0.3.30" }
futures-buffered = { version = "0.2.4" }
ignore = { version = "0.4.22" }
libaes = { version = "0.7.0" }
lofty = { version = "0.18.2" }
lrc = { git = "https://github.com/vnghia/lrc.git", rev = "875a540" }
mimalloc = { version = "0.1.39" }
mime_guess = { version = "2.0.4" }
rayon = { version = "1.10.0" }
rsmpeg = { git = "https://github.com/vnghia/rsmpeg.git", rev = "e34a83a", features = [
  "link_system_ffmpeg",
] }
thiserror = { version = "1.0.58" }
tokio = { version = "1.37.0", features = ["full"] }
tokio-postgres = { version = "0.7.10" }
tokio-util = { version = "0.7.10", features = ["io"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.2", features = ["cors", "fs", "trace"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = { version = "2.5.0" }
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }

[dev-dependencies]
fake = { workspace = true }
serde_json = { workspace = true }

nghe-types = { path = "types", features = ["test"] }

http-body-util = { version = "0.1.1" }
image = { version = "0.25.1", default-features = false, features = [
  "jpeg",
  "png",
] }
tempfile = "3.10.1"
url = "2.5.0"
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }

[target.'cfg(not(target_env = "musl"))'.dev-dependencies]
diesel = { version = "2.1.5", features = ["postgres"] }

[profile.release]
opt-level = 3
strip = "debuginfo"
overflow-checks = false
lto = "fat"
panic = "abort"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true

[package.metadata.vcpkg]
dependencies = [
  "ffmpeg[avcodec,avfilter,avformat,avresample,mp3lame,opus,soxr,swresample,vorbis]",
]
git = "https://github.com/microsoft/vcpkg"
rev = "2023.11.20"
overlay-triplets-path = "vcpkg/triplets/"

[package.metadata.vcpkg.target]
x86_64-unknown-linux-gnu = { triplet = "x64-linux-release" }
aarch64-unknown-linux-gnu = { triplet = "arm64-linux-release" }

x86_64-unknown-linux-musl = { triplet = "x64-linux-musl-release" }
aarch64-unknown-linux-musl = { triplet = "arm64-linux-musl-release" }

x86_64-apple-darwin = { triplet = "x64-osx-release" }
aarch64-apple-darwin = { triplet = "arm64-osx-release" }

x86_64-pc-windows-msvc = { triplet = "x64-windows-static-release" }
