workspace = { members = ["src/proc_macros"] }

[package]
name = "nghe"
version = "0.1.0"
edition = "2021"
default-run = "nghe"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
axum = { version = "0.7.4", features = ["macros"] }
concat-string = "1.0.1"
config = "0.13.4"
derivative = "2.2.0"
futures = "0.3.30"
itertools = "0.12.0"
libaes = "0.7.0"
md5 = "0.7.0"
mimalloc = "0.1.39"
nghe-proc_macros = { path = "src/proc_macros", version = "0.1.0" }
paste = "1.0.14"
rand = "0.8.5"
sea-orm = { version = "0.12.11", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
  "with-uuid",
  "with-time",
] }
sea-orm-migration = "0.12.10"
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.4.0", features = ["hex"] }
time = "0.3.31"
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5.1", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = "1.6.1"
walkdir = "2.4.0"

[build-dependencies]
built = "0.7"

[[bin]]
name = "nghe"
path = "src/main.rs"

[[bin]]
name = "sea-cli"
path = "src/migrator/main.rs"

[dev-dependencies]
fake = { version = "2.9.2", features = [
  "derive",
  "uuid",
  "serde_json",
  "time",
] }
http-body-util = "0.1.0"
serde_json = "1.0.111"
tempdir = "0.3.7"
url = "2.5.0"
uuid = { version = "1.6.1", features = ["v4", "fast-rng"] }
