workspace = { members = ["src/proc_macros"] }

[package]
name = "nghe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.77"
axum = { version = "0.7.4", features = ["macros"] }
axum-extra = { version = "0.9.2", features = ["form"] }
concat-string = "1.0.1"
crossbeam-channel = "0.5.12"
derivative = "2.2.0"
diesel = { version = "2.1.4", features = ["uuid", "time"] }
diesel-async = { version = "0.4.1", features = [
  "postgres",
  "deadpool",
  "async-connection-wrapper",
] }
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
figment = { version = "0.10.14", features = ["env"] }
futures = "0.3.30"
ignore = "0.4.22"
isolang = { version = "2.4.0", default-features = false }
itertools = "0.12.1"
libaes = "0.7.0"
lofty = "0.18.2"
md5 = "0.7.0"
mimalloc = "0.1.39"
nghe-proc_macros = { path = "src/proc_macros", version = "0.1.0" }
paste = "1.0.14"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.7.0", features = ["hex"] }
thiserror = "1.0.57"
time = { version = "0.3.34", features = ["serde-human-readable", "macros"] }
tokio = { version = "1.36", features = ["full"] }
tokio-postgres = "0.7.10"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.7.0", features = ["v4", "serde"] }
walkdir = "2.5.0"
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }

[build-dependencies]
built = "0.7"

[dev-dependencies]
fake = { version = "2.9.2", features = [
  "derive",
  "uuid",
  "serde_json",
  "time",
] }
http-body-util = "0.1.1"
serde_json = "1.0.114"
tempfile = "3.10.1"
url = "2.5.0"
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }

[target.'cfg(not(target_env = "musl"))'.dev-dependencies]
diesel = { version = "2.1.4", features = ["postgres"] }

[profile.release]
opt-level = 3
strip = "debuginfo"
overflow-checks = false
lto = "fat"
panic = "abort"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true
