[workspace]
members = ["proc_macros"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "nghe"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
async-trait = "0.1.79"
axum = { version = "0.7.5", features = ["http2", "macros"] }
axum-extra = { version = "0.9.3", features = ["form"] }
concat-string = "1.0.1"
constcat = "0.5.0"
derivative = "2.2.0"
diesel = { version = "2.1.5", features = ["uuid", "time"] }
diesel-async = { version = "0.4.1", features = [
  "postgres",
  "deadpool",
  "async-connection-wrapper",
] }
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
figment = { version = "0.10.15", features = ["env"] }
flume = { version = "0.11.0", features = ["async"] }
futures = "0.3.30"
futures-buffered = "0.2.4"
hex = "0.4.3"
ignore = "0.4.22"
isolang = { version = "2.4.0", default-features = false }
itertools = "0.12.1"
libaes = "0.7.0"
lofty = "0.18.2"
md5 = "0.7.0"
mimalloc = "0.1.39"
mime_guess = "2.0.4"
nghe-proc_macros = { path = "proc_macros" }
paste = "1.0.14"
rand = "0.8.5"
rayon = "1.10.0"
rsmpeg = { git = "https://github.com/vnghia/rsmpeg.git", rev = "e34a83a", features = [
  "link_system_ffmpeg",
] }
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.7.0", features = ["hex"] }
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.58"
time = { version = "0.3.34", features = ["serde-human-readable", "macros"] }
tokio = { version = "1.37", features = ["full"] }
tokio-postgres = "0.7.10"
tokio-util = { version = "0.7.10", features = ["io"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
urlencoding = "2.1.3"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
walkdir = "2.5.0"
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }

[build-dependencies]
built = { version = "0.7", features = ["git2"] }

[dev-dependencies]
fake = { version = "2.9.2", features = [
  "derive",
  "uuid",
  "serde_json",
  "time",
] }
http-body-util = "0.1.1"
serde_json = "1.0.115"
tempfile = "3.10.1"
url = "2.5.0"
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }

[target.'cfg(not(target_env = "musl"))'.dev-dependencies]
diesel = { version = "2.1.5", features = ["postgres"] }

[profile.release]
opt-level = 3
strip = "debuginfo"
overflow-checks = false
lto = "fat"
panic = "abort"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true

[package.metadata.vcpkg]
dependencies = [
  "ffmpeg[avcodec,avfilter,avformat,avresample,mp3lame,opus,soxr,swresample,vorbis]",
]
git = "https://github.com/microsoft/vcpkg"
rev = "2023.11.20"
overlay-triplets-path = "vcpkg/triplets/"

[package.metadata.vcpkg.target]
x86_64-unknown-linux-gnu = { triplet = "x64-linux-release" }
aarch64-unknown-linux-gnu = { triplet = "arm64-linux-release" }

x86_64-unknown-linux-musl = { triplet = "x64-linux-musl-release" }
aarch64-unknown-linux-musl = { triplet = "arm64-linux-musl-release" }

x86_64-apple-darwin = { triplet = "x64-osx-release" }
aarch64-apple-darwin = { triplet = "arm64-osx-release" }

x86_64-pc-windows-msvc = { triplet = "x64-windows-static-release" }
