[package]
name = "nghe"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.3"
config = "0.13.4"
paste = "1.0.14"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.8.0"
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5.0", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
built = "0.7"
