[build.env]
passthrough = ["DATABASE_URL"]

[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get --assume-yes install libpq-dev:$CROSS_DEB_ARCH",
  "curl -L --retry 10 https://github.com/rui314/mold/releases/download/v2.4.0/mold-2.4.0-x86_64-linux.tar.gz | tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
  "curl -L --retry 10 https://github.com/rui314/mold/releases/download/v2.4.0/mold-2.4.0-x86_64-linux.tar.gz | tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
  "curl -L --retry 10 https://github.com/rui314/mold/releases/download/v2.4.0/mold-2.4.0-x86_64-linux.tar.gz | tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -",
]
