[build.env]
passthrough = ["DATABASE_URL"]

[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get --assume-yes install libpq-dev:$CROSS_DEB_ARCH",
  "MOLD_VERSION=2.4.0 curl -L --retry 10 --silent --show-error https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-$(uname -m)-linux.tar.gz | tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
  "MOLD_VERSION=2.4.0 curl -L --retry 10 --silent --show-error https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-$(uname -m)-linux.tar.gz | tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
  "MOLD_VERSION=2.4.0 curl -L --retry 10 --silent --show-error https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-$(uname -m)-linux.tar.gz | tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -",
]
