[application]
name = "nghe-frontend"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"
sub_package = "frontend"

[web.app]
title = "nghe"

[web.watcher]
reload_html = true
watch_path = ["src", "assets", "public"]

[web.resource]
style = []

[web.resource.dev]
script = []

[[web.proxy]]
backend = "http://localhost:3000/rest"
