//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[cfg_attr(test, derive(fake::Dummy))]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    #[serde(skip_serializing)]
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub password: Vec<u8>,
    pub email: String,
    pub admin_role: bool,
    pub download_role: bool,
    pub share_role: bool,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_music_folder::Entity")]
    UserMusicFolder,
}

impl Related<super::user_music_folder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMusicFolder.def()
    }
}

impl Related<super::music_folder::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_music_folder::Relation::MusicFolder.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_music_folder::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
