[workspace]

[package]
name = "vcpkg"
version = "0.1.0"
edition = "2021"

[package.metadata.vcpkg]
dependencies = ["vcpkg-cmake"]
git = "https://github.com/microsoft/vcpkg"
rev = "2023.11.20"
overlay-triplets-path = "vcpkg/triplets/"
