#TODO: enable mold for other target
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

#TODO: support more targets after https://github.com/rust-lang/cargo/issues/10273
[env]
PKG_CONFIG_ALLOW_CROSS = { value = "true" }
FFMPEG_PKG_CONFIG_PATH = { value = "vcpkg/target/vcpkg/installed/x64-linux-release/lib/pkgconfig", relative = true }
