#TODO: enable mold for other target
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

#TODO: support more targets after https://github.com/rust-lang/cargo/issues/10273
[env]
VCPKG_ROOT = { value = "vcpkg/target/vcpkg", relative = true }
PKG_CONFIG_ALLOW_CROSS = { value = "true" }
FFMPEG_PKG_CONFIG_PATH = { value = "vcpkg/target/vcpkg/installed/x64-linux-release/lib/pkgconfig", relative = true }

# Only Windows uses vcpkg linking.
VCPKGRS_TRIPLET = { value = "x64-windows-static-release" }
