#TODO: enable mold for other target
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "link-arg=Mfplat.lib",
  "-C",
  "link-arg=Strmiids.lib",
  "-C",
  "link-arg=Mfuuid.lib",
  "-C",
  "link-arg=Bcrypt.lib",
  "-C",
  "link-arg=Secur32.lib",
  "-C",
  "link-arg=Ole32.lib",
  "-C",
  "link-arg=User32.lib",
]

#TODO: support more targets after https://github.com/rust-lang/cargo/issues/10273
[env]
VCPKG_ROOT = { value = "vcpkg/target/vcpkg", relative = true }
PKG_CONFIG_ALLOW_CROSS = { value = "true" }

PKG_CONFIG_PATH_x86_64-unknown-linux-gnu = { value = "vcpkg/target/vcpkg/installed/x64-linux-release/lib/pkgconfig", relative = true }
PKG_CONFIG_PATH_aarch64-unknown-linux-gnu = { value = "vcpkg/target/vcpkg/installed/arm64-linux-release/lib/pkgconfig", relative = true }
PKG_CONFIG_PATH_aarch64-apple-darwin = { value = "vcpkg/target/vcpkg/installed/arm64-osx-release/lib/pkgconfig", relative = true }
