#TODO: enable mold for other target
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

#TODO: support more targets after https://github.com/rust-lang/cargo/issues/10273
[env]
FFMPEG_PKG_CONFIG_PATH = { value = "vcpkg/target/vcpkg/installed/x64-linux-release/lib/pkgconfig", relative = true }

# Windows
FFMPEG_INCLUDE_DIR = { value = "vcpkg\\target\\vcpkg\\installed\\x64-windows-static-release\\include", relative = true }
FFMPEG_LIBS_DIR = { value = "vcpkg\\target\\vcpkg\\installed\\x64-windows-static-release\\lib", relative = true }
