name: "Extract build information"
description: "Extract build information"
inputs:
  target:
    description: "Rust target"
    required: true
runs:
  using: "composite"
  steps:
    - name: Extract build information
      env:
        TARGET: ${{ inputs.target }}
      run: |
        echo "env=${TARGET##*-}" >> "$GITHUB_OUTPUT"
        echo "arch=$(echo $TARGET | cut -d '-' -f1)" >> "$GITHUB_OUTPUT"
        echo "docker-arch=${{ startsWith(inputs.target, 'x86_64') && 'amd64' || 'arm64' }}" >> "$GITHUB_OUTPUT"
        echo "profile=${{ (github.event_name == 'release' || github.event_name == 'workflow_dispatch') && 'release' || 'dev' }}" >> "$GITHUB_OUTPUT"
        echo "output-dir=${{ (github.event_name == 'release' || github.event_name == 'workflow_dispatch') && 'release' || 'debug' }}" >> "$GITHUB_OUTPUT"
