name: "Extract build information"
description: "Extract build information"
inputs:
  target:
    description: "Rust target"
    required: true
outputs:
  env:
    description: "env"
    value: ${{ steps.build.outputs.env }}
  arch:
    description: "arch"
    value: ${{ steps.build.outputs.arch }}
  docker-arch:
    description: "docker-arch"
    value: ${{ steps.build.outputs.docker-arch }}
  profile:
    description: "profile"
    value: ${{ steps.build.outputs.profile }}
  output-dir:
    description: "output-dir"
    value: ${{ steps.build.outputs.output-dir }}
runs:
  using: "composite"
  steps:
    - name: Extract build information
      id: build
      shell: bash
      env:
        TARGET: ${{ inputs.target }}
      run: |
        echo "env=${TARGET##*-}" >> "$GITHUB_OUTPUT"
        echo "arch=$(echo $TARGET | cut -d '-' -f1)" >> "$GITHUB_OUTPUT"
        echo "docker-arch=${{ startsWith(inputs.target, 'x86_64') && 'amd64' || 'arm64' }}" >> "$GITHUB_OUTPUT"
        echo "profile=${{ (github.event_name == 'release' || github.event_name == 'workflow_dispatch') && 'release' || 'dev' }}" >> "$GITHUB_OUTPUT"
        echo "output-dir=${{ (github.event_name == 'release' || github.event_name == 'workflow_dispatch') && 'release' || 'debug' }}" >> "$GITHUB_OUTPUT"
