[package]
name = "nghe-proc-macro"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
bon = { workspace = true }
concat-string = { workspace = true }
convert_case = { workspace = true }

darling = { version = "0.24.1" }
proc-macro2 = { version = "1.0.95" }
quote = { version = "1.0.40" }
syn = { version = "3.0.6", features = ["fold", "full"] }
