name: Main

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_LOG: nghe_backend=trace
  COLORBT_SHOW_HIDDEN: 1
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://localhost:9090
  AWS_USE_PATH_STYLE_ENDPOINT: true
  POSTGRES_VERSION: 17
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - shell: default
            runs-on: ubuntu-latest
          - shell: musl
            runs-on: ubuntu-latest
          - shell: default
            runs-on: ubuntu-24.04-arm
          - shell: musl
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.platform.runs-on }}

    services: &services
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: md5
          POSTGRES_INITDB_ARGS: --auth-host=md5
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres
        ports:
          - 5432:5432
      s3:
        image: adobe/s3mock:latest
        ports:
          - 9090:9090

    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: nghe
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        run: nix develop .#${{ matrix.platform.shell }} --accept-flake-config --command cargo build --package nghe_backend
