name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_LOG: nghe_backend=trace
  COLORBT_SHOW_HIDDEN: 1
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://localhost:9090
  AWS_USE_PATH_STYLE_ENDPOINT: true
  POSTGRES_VERSION: 17
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            runs-on: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            runs-on: ubuntu-24.04-arm
          - target: aarch64-unknown-linux-musl
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.platform.runs-on }}

    services: &services
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: md5
          POSTGRES_INITDB_ARGS: --auth-host=md5
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres
        ports:
          - 5432:5432
      s3:
        image: adobe/s3mock:latest
        ports:
          - 9090:9090

    steps:
      - uses: actions/checkout@v6

      - name: Install yq
        uses: ./.github/actions/install-yq

      - name: Extract build information
        id: build
        uses: ./.github/actions/extract-build-information

      - name: Setup rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: ${{ matrix.platform.target }}-${{ steps.build.outputs.profile }}

      - name: Increase postgres max connection
        run: |
          docker exec postgres psql -U postgres -d postgres -c "ALTER SYSTEM SET max_connections = '1000'";
          docker exec postgres psql -U postgres -d postgres -c "ALTER SYSTEM SET shared_buffers = '2048MB'";
          docker restart postgres

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v17
        with:
          name: nghe
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix develop .#${{ steps.build.outputs.vendor }} --accept-flake-config --command cargo build --locked --package nghe_backend
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.docker-arch }}-${{ steps.build.outputs.vendor }}
          path: ${{ github.workspace }}/target/${{ matrix.platform.target }}/${{ steps.build.outputs.output-dir }}/nghe_backend
          retention-days: 1

      - name: Test
        run: nix develop .#${{ steps.build.outputs.vendor }} --accept-flake-config --command cargo nextest run --locked --profile ci --cargo-profile ${{ steps.build.outputs.profile }} --workspace --exclude nghe_frontend
        env:
          LASTFM_KEY: ${{ steps.build.outputs.docker-arch == 'amd64' && secrets.LASTFM_KEY || '' }}
          SPOTIFY_ID: ${{ steps.build.outputs.docker-arch == 'amd64' && secrets.SPOTIFY_ID || '' }}
          SPOTIFY_SECRET: ${{ steps.build.outputs.docker-arch == 'amd64' && secrets.SPOTIFY_SECRET || '' }}
      - name: Upload test report to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          disable_search: true
          report_type: "test_results"
          fail_ci_if_error: true

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: aarch64-apple-darwin
            runs-on: macos-latest

    runs-on: ${{ matrix.platform.runs-on }}

    env:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v6

      - name: Install yq
        uses: ./.github/actions/install-yq

      - name: Extract build information
        id: build
        uses: ./.github/actions/extract-build-information

      - name: Setup rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: ${{ matrix.platform.target }}-${{ steps.build.outputs.profile }}

      - name: Install and setup postgres
        run: |
          brew install postgresql@${{ env.POSTGRES_VERSION }}
          brew link postgresql@${{ env.POSTGRES_VERSION }}
          export PGDATA="$RUNNER_TEMP/pgdata"
          initdb --username=postgres --encoding="UTF-8" --locale="en_US.UTF-8" --pwfile=<(echo postgres)
          pg_ctl start
          psql -U postgres -d postgres -c "ALTER SYSTEM SET max_connections = '1000'"
          psql -U postgres -d postgres -c "ALTER SYSTEM SET shared_buffers = '2048MB'"
          pg_ctl restart
      - name: Install and setup minio
        run: |
          brew install minio
          minio server --address=':9090' data &

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v17
        with:
          name: nghe
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix develop .#default --accept-flake-config --command cargo build --locked --package nghe_backend
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.docker-arch }}-${{ steps.build.outputs.vendor }}
          path: ${{ github.workspace }}/target/${{ matrix.platform.target }}/${{ steps.build.outputs.output-dir }}/nghe_backend
          retention-days: 1

      - name: Test
        run: nix develop .#default --accept-flake-config --command cargo nextest run --locked --profile ci --cargo-profile ${{ steps.build.outputs.profile }} --workspace --exclude nghe_frontend
        env:
          LASTFM_KEY: ${{ steps.build.outputs.docker-arch == 'arm64' && secrets.LASTFM_KEY || '' }}
          SPOTIFY_ID: ${{ steps.build.outputs.docker-arch == 'arm64' && secrets.SPOTIFY_ID || '' }}
          SPOTIFY_SECRET: ${{ steps.build.outputs.docker-arch == 'arm64' && secrets.SPOTIFY_SECRET || '' }}
      - name: Upload test report to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          disable_search: true
          report_type: "test_results"
          fail_ci_if_error: true

  build-coverage:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest

    runs-on: ${{ matrix.platform.runs-on }}

    services: *services

    steps:
      - uses: actions/checkout@v6

      - name: Install yq
        uses: ./.github/actions/install-yq

      - name: Setup rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: coverage

      - name: Increase postgres max connection
        run: |
          docker exec postgres psql -U postgres -d postgres -c "ALTER SYSTEM SET max_connections = '1000'";
          docker exec postgres psql -U postgres -d postgres -c "ALTER SYSTEM SET shared_buffers = '2048MB'";
          docker restart postgres

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v17
        with:
          name: nghe
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Generate code coverage
        run: nix develop .#coverage --accept-flake-config --command cargo tarpaulin --locked --workspace --exclude nghe_frontend --engine llvm --out xml
        env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
          SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true
          report_type: "coverage"
          fail_ci_if_error: true
