name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_LOG: nghe-backend=trace
  COLORBT_SHOW_HIDDEN: 1

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            runs-on: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            runs-on: ubuntu-24.04-arm
          - target: aarch64-unknown-linux-musl
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - uses: actions/checkout@v7

      - name: Install yq
        uses: ./.github/actions/install-yq

      - name: Extract build information
        id: build
        uses: ./.github/actions/extract-build-information
        with:
          target: ${{ matrix.platform.target }}

      - name: Setup rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: ${{ matrix.platform.target }}-${{ steps.build.outputs.profile }}

      - name: Setup nix
        uses: ./.github/actions/setup-nix
        with:
          cache-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: ${{ steps.build.outputs.vendor }}

      - name: Build
        run: nix develop .#${{ steps.build.outputs.vendor }} --command cargo build --locked --package nghe-backend
      - name: Patch ELF
        if: ${{ steps.build.outputs.env != 'musl' }}
        run: nix run nixpkgs#patchelf -- --set-interpreter /lib64/ld-linux-x86-64.so.2 ${{ github.workspace }}/target/${{ matrix.platform.target }}/${{ steps.build.outputs.output-dir }}/nghe-backend
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.docker-arch }}-${{ steps.build.outputs.vendor }}
          path: ${{ github.workspace }}/target/${{ matrix.platform.target }}/${{ steps.build.outputs.output-dir }}/nghe-backend
          retention-days: 1

      - name: Run test services
        run: nix develop --command docker compose -f ci/test/docker-compose.yaml up -d
      - name: Test
        run: nix develop .#${{ steps.build.outputs.vendor }} --command cargo nextest run --locked --profile ci --cargo-profile ${{ steps.build.outputs.profile }} --workspace --exclude nghe-frontend
        env:
          LASTFM_KEY: ${{ steps.build.outputs.docker-arch == 'amd64' && secrets.LASTFM_KEY || '' }}
      - name: Upload test report to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          disable_search: true
          report_type: "test_results"
          fail_ci_if_error: true

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: aarch64-apple-darwin
            runs-on: macos-latest

    runs-on: ${{ matrix.platform.runs-on }}

    env:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v7

      - name: Install yq
        uses: ./.github/actions/install-yq

      - name: Extract build information
        id: build
        uses: ./.github/actions/extract-build-information
        with:
          target: ${{ matrix.platform.target }}

      - name: Setup rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: ${{ matrix.platform.target }}-${{ steps.build.outputs.profile }}

      - name: Setup nix
        uses: ./.github/actions/setup-nix
        with:
          cache-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: default

      - name: Build
        run: nix develop .#default --command cargo build --locked --package nghe-backend
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.docker-arch }}-macos
          path: ${{ github.workspace }}/target/${{ matrix.platform.target }}/${{ steps.build.outputs.output-dir }}/nghe-backend
          retention-days: 1

      - name: Run test services
        run: |
          nix develop --command bash -c 'initdb --username=${POSTGRES_USER} --pwfile=<(echo ${POSTGRES_PASSWORD}) --pgdata=${RUNNER_TEMP}/postgres --encoding="UTF-8" --locale="en_US.UTF-8" --set "max_connections = 1000" --set "shared_buffers = 2048MB"'
          nix develop --command bash -c 'pg_ctl start --pgdata=${RUNNER_TEMP}/postgres'

          nix develop --command bash -c 'weed mini -dir=${RUNNER_TEMP}/weed -s3.port=${AWS_PORT} &'
      - name: Test
        run: nix develop .#default --command cargo nextest run --locked --profile ci --cargo-profile ${{ steps.build.outputs.profile }} --workspace --exclude nghe-frontend
        env:
          LASTFM_KEY: ${{ steps.build.outputs.docker-arch == 'arm64' && secrets.LASTFM_KEY || '' }}
      - name: Upload test report to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          disable_search: true
          report_type: "test_results"
          fail_ci_if_error: true

  build-freebsd:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-freebsd
            runs-on: ubuntu-latest

    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - uses: actions/checkout@v7

      - name: Install yq
        uses: ./.github/actions/install-yq

      - name: Extract build information
        id: build
        uses: ./.github/actions/extract-build-information
        with:
          target: ${{ matrix.platform.target }}

      - name: Setup rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: ${{ matrix.platform.target }}-${{ steps.build.outputs.profile }}

      - name: Setup nix
        uses: ./.github/actions/setup-nix
        with:
          cache-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: freebsd

      - name: Build
        run: nix develop .#freebsd --command cargo build --locked --package nghe-backend
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.docker-arch }}-freebsd
          path: ${{ github.workspace }}/target/${{ matrix.platform.target }}/${{ steps.build.outputs.output-dir }}/nghe-backend
          retention-days: 1

  build-coverage:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest

    runs-on: ${{ matrix.platform.runs-on }}
    if: ${{ github.event_name != 'release' }}

    steps:
      - uses: actions/checkout@v7

      - name: Install yq
        uses: ./.github/actions/install-yq

      - name: Setup rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: coverage

      - name: Setup nix
        uses: ./.github/actions/setup-nix
        with:
          cache-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: coverage

      - name: Run test services
        run: nix develop --command docker compose -f ci/test/docker-compose.yaml up -d
      - name: Generate code coverage
        run: nix develop .#coverage --command cargo llvm-cov nextest --profile ci --workspace --codecov --output-path codecov.json --exclude nghe-frontend
        env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
      - name: Upload test report to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          disable_search: true
          report_type: "test_results"
          fail_ci_if_error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          disable_search: true
          report_type: "coverage"
          fail_ci_if_error: true

  build-docker:
    runs-on: ubuntu-latest
    if: ${{ vars.BUILD_DOCKER != '' }}

    needs: [build-linux]

    env:
      DOCKER_BUILD_RECORD_UPLOAD: false

    steps:
      - uses: actions/checkout@v7
      - name: Download build artifact for docker
        uses: actions/download-artifact@v8
        with:
          path: ${{ github.workspace }}/artifact/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      # GNU
      - name: Extract metadata for Docker gnu
        id: meta-gnu
        uses: docker/metadata-action@v6
        with:
          images: |
            name=ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=raw,value=develop,enable={{is_default_branch}}
      - name: Build and push gnu
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ci/docker/Dockerfile
          build-args: |
            BASE_IMAGE=gcr.io/distroless/base-nossl-debian13:latest
            TARGET_ENV=gnu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-gnu.outputs.tags }}

      # Musl
      - name: Extract metadata for Docker musl
        id: meta-musl
        uses: docker/metadata-action@v6
        with:
          images: |
            name=ghcr.io/${{ github.repository }}
          flavor: |
            suffix=-scratch,onlatest=true
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=raw,value=develop,enable={{is_default_branch}}
      - name: Build and push musl
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ci/docker/Dockerfile
          build-args: |
            BASE_IMAGE=scratch
            TARGET_ENV=musl
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-musl.outputs.tags }}

  upload-release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}

    needs: [build-linux, build-macos, build-freebsd]

    permissions:
      contents: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          path: ${{ github.workspace }}/artifact/
      - name: Upload release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find artifact/ -mindepth 1 -maxdepth 1 -type d -exec zip -r --move --test {}.zip {} \;
          gh release upload ${{ github.ref_name }} \
            artifact/amd64-gnu.zip \
            artifact/amd64-musl.zip \
            artifact/arm64-gnu.zip \
            artifact/arm64-musl.zip \
            artifact/arm64-darwin.zip \
            artifact/amd64-freebsd.zip
