name: Release please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: dev/release-please/config.json
          manifest-file: dev/release-please/manifest.json

      - uses: actions/checkout@v7
        if: ${{ steps.release-please.outputs.release_created }}
      - name: Trigger release build pipeline
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: gh workflow run main.yaml -f release-tag=${{ steps.release-please.outputs.tag_name }}
